services:
  backend:
    build:
      context: .
    ports:
      - "3008:3008"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://jim2:rttm@db:5432/RTTM
      - DB_USER=jim2
      - DB_PASSWORD=rttm
      - DB_NAME=RTTM
      - DB_HOST=db
      - DB_PORT=5432
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: jim2
      POSTGRES_PASSWORD: rttm
      POSTGRES_DB: RTTM
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
